
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Domain file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (domain nut_assembly)
    (:requirements :typing :equality)
    (:types
        gripper - object
        table - object
        tabletop-object - object
        nut - tabletop-object
        peg - tabletop-object
        round-peg - peg
        square-peg - peg
        round-nut - nut
        square-nut - nut
        object
    )

    (:constants
        
    )

    (:predicates
        (can-pick-up ?x1 - tabletop-object)
        (on-table ?x1 - tabletop-object ?x2 - table)
        (on ?x1 - nut ?x2 - peg)
        (occupying-gripper ?x1 - tabletop-object ?x2 - gripper)
        (match ?x1 - nut ?x2 - peg)
        (free ?x1 - gripper)
    )

    (:functions
        
    )

    

    
    (:action pick-up-nut-from-tabletop
     :parameters (?nut - nut ?table - table ?gripper - gripper)
     :precondition (and (on-table ?nut ?table) (can-pick-up ?nut) (free ?gripper))
     :effect (and
        (occupying-gripper ?nut ?gripper)
        (not (on-table ?nut ?table))
        (not (free ?gripper)))
    )


    (:action free-gripper
     :parameters (?tabletop-object - tabletop-object ?gripper - gripper)
     :precondition (and (not (can-pick-up ?tabletop-object)) (occupying-gripper ?tabletop-object ?gripper) (not (free ?gripper)))
     :effect (and
        (not (occupying-gripper ?tabletop-object ?gripper))
        (free ?gripper))
    )


    (:action put-nut-on-peg
     :parameters (?nut - nut ?peg - peg ?gripper - gripper)
     :precondition (and (match ?nut ?peg) (occupying-gripper ?nut ?gripper) (not (free ?gripper)))
     :effect (and
        (on ?nut ?peg)
        (not (occupying-gripper ?nut ?gripper))
        (free ?gripper))
    )


    (:action remove-nut-from-peg
     :parameters (?gripper - gripper ?nut - nut ?peg - peg)
     :precondition (and (free ?gripper) (on ?nut ?peg))
     :effect (and
        (not (free ?gripper))
        (not (on ?nut ?peg))
        (occupying-gripper ?nut ?gripper))
    )

)