
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Domain file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (domain nut_assembly)
    (:requirements :typing :equality)
    (:types
        gripper - object
        table - object
        tabletop-object - object
        nut - tabletop-object
        peg - tabletop-object
        round-peg - peg
        square-peg - peg
        round-nut - nut
        square-nut - nut
        object
    )

    (:constants
        
    )

    (:predicates
        (small-enough-for-gripper-to-pick-up ?x1 - tabletop-object ?x2 - gripper)
        (directly-on-table ?x1 - tabletop-object ?x2 - table)
        (on-peg ?x1 - nut ?x2 - peg)
        (exclusively-occupying-gripper ?x1 - tabletop-object ?x2 - gripper)
        (shapes-match ?x1 - nut ?x2 - peg)
        (free ?x1 - gripper)
    )

    (:functions
        
    )

    

    
    (:action pick-up-nut-from-tabletop
     :parameters (?nut - nut ?table - table ?gripper - gripper)
     :precondition (and (directly-on-table ?nut ?table) (small-enough-for-gripper-to-pick-up ?nut ?gripper) (free ?gripper))
     :effect (and
        (exclusively-occupying-gripper ?nut ?gripper)
        (not (directly-on-table ?nut ?table))
        (not (free ?gripper)))
    )


    (:action put-nut-on-peg
     :parameters (?nut - nut ?peg - peg ?gripper - gripper)
     :precondition (and (shapes-match ?nut ?peg) (exclusively-occupying-gripper ?nut ?gripper) (not (free ?gripper)))
     :effect (and
        (on-peg ?nut ?peg)
        (not (exclusively-occupying-gripper ?nut ?gripper))
        (free ?gripper))
    )


    (:action pick-up-nut-from-peg
     :parameters (?gripper - gripper ?round-peg - round-peg ?square-nut - square-nut)
     :precondition (and (free ?gripper) (not (exclusively-occupying-gripper ?round-peg ?gripper)) (not (exclusively-occupying-gripper ?square-nut ?gripper)) (not (shapes-match ?square-nut ?round-peg)) (not (small-enough-for-gripper-to-pick-up ?round-peg ?gripper)) (on-peg ?square-nut ?round-peg) (small-enough-for-gripper-to-pick-up ?square-nut ?gripper))
     :effect (and
        (exclusively-occupying-gripper ?square-nut ?gripper)
        (not (free ?gripper))
        (not (on-peg ?square-nut ?round-peg)))
    )

)