
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Domain file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (domain coffee)
    (:requirements :equality :typing)
    (:types
        mug - object
        coffee-pod - object
        coffee-pod-holder - object
        coffee-machine-lid - object
        drawer - object
        table - object
        gripper - object
        object
    )

    (:constants
        
    )

    (:predicates
        (can-hold ?x1 - object)
        (can-open ?x1 - object)
        (can-contain ?x1 - object ?x2 - object)
        (on-table ?x1 - object ?x2 - table)
        (holding ?x1 - object)
        (in ?x1 - object ?x2 - object)
        (open ?x1 - object)
        (free ?x1 - gripper)
        (under ?x1 - object ?x2 - object)
    )

    (:functions
        
    )

    

    
    (:action pick-up-tabletop
     :parameters (?obj - object ?table - table ?gripper - gripper)
     :precondition (and (on-table ?obj ?table) (can-hold ?obj) (free ?gripper))
     :effect (and
        (holding ?obj)
        (not (on-table ?obj ?table))
        (not (free ?gripper)))
    )


    (:action open-coffee-pod-holder
     :parameters (?holder - coffee-pod-holder ?lid - coffee-machine-lid ?gripper - gripper)
     :precondition (and (not (open ?holder)) (can-open ?holder) (free ?gripper))
     :effect (and
        (open ?holder))
    )


    (:action close-coffee-pod-holder
     :parameters (?holder - coffee-pod-holder ?lid - coffee-machine-lid ?gripper - gripper)
     :precondition (and (open ?holder) (free ?gripper))
     :effect (and
        (not (open ?holder)))
    )


    (:action place-pod-in-holder
     :parameters (?pod - coffee-pod ?holder - coffee-pod-holder ?gripper - gripper)
     :precondition (and (holding ?pod) (open ?holder) (can-contain ?holder ?pod) (not (free ?gripper)))
     :effect (and
        (not (holding ?pod))
        (in ?pod ?holder)
        (free ?gripper))
    )


    (:action place-mug-under-holder
     :parameters (?mug - mug ?holder - coffee-pod-holder ?gripper - gripper)
     :precondition (holding ?mug)
     :effect (and
        (under ?mug ?holder)
        (not (holding ?mug))
        (free ?gripper))
    )

    '(:action pick-up-from-drawer\n    :parameters (?obj - object ?drawer - drawer ?gripper - gripper)\n    :precondition (and (in ?obj ?drawer) (can-hold ?obj) (free ?gripper) (open ?drawer))\n    :effect (and (holding ?obj) (not (in ?obj ?drawer)) (not (free ?gripper)))\n)\n\n(:action close-drawer\n    :parameters (?drawer - drawer ?gripper - gripper)\n    :precondition (and (open ?drawer) (free ?gripper))\n    :effect (not (open ?drawer))\n)'

)