
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Domain file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (domain tabletop)
    (:requirements :typing :equality)
    (:types
        robot - object
        holdable - object
        opennable - object
        support - object
        gripper - robot
        mug - holdable
        coffee-pod - holdable
        coffee-machine-lid - holdable
        container - opennable
        table - support
        coffee-pod-holder - container
        drawer - container
        object
    )

    (:constants
        
    )

    (:predicates
        (holding ?x1 - holdable)
        (open ?x1 - opennable)
        (free ?x1 - gripper)
        (on ?x1 - holdable ?x2 - support)
        (in ?x1 - holdable ?x2 - container)
        (under ?x1 - object ?x2 - object)
    )

    (:functions
        
    )

    

    
    (:action pick-up
     :parameters (?obj - holdable ?table - table ?gripper - gripper)
     :precondition (and (free ?gripper) (on ?obj ?table))
     :effect (and
        (holding ?obj)
        (not (on ?obj ?table))
        (not (free ?gripper)))
    )


    (:action release-holding
     :parameters (?held - holdable ?gripper - gripper)
     :precondition (and (not (free ?gripper)) (holding ?held))
     :effect (and
        (free ?gripper)
        (not (holding ?held)))
    )


    (:action open-coffee-pod-holder
     :parameters (?holder - coffee-pod-holder ?lid - coffee-machine-lid ?gripper - gripper)
     :precondition (and (not (open ?holder)) (free ?gripper))
     :effect (and
        (open ?holder)
        (free ?gripper))
    )


    (:action place-pod-in-holder
     :parameters (?pod - coffee-pod ?holder - coffee-pod-holder ?gripper - gripper)
     :precondition (and (holding ?pod) (open ?holder) (not (free ?gripper)))
     :effect (and
        (not (holding ?pod))
        (in ?pod ?holder)
        (free ?gripper))
    )


    (:action close-coffee-pod-holder
     :parameters (?holder - coffee-pod-holder ?lid - coffee-machine-lid ?gripper - gripper)
     :precondition (and (open ?holder) (free ?gripper))
     :effect (and
        (not (open ?holder))
        (free ?gripper))
    )


    (:action place-mug-under-holder
     :parameters (?mug - mug ?holder - coffee-pod-holder ?table - table ?gripper - gripper)
     :precondition (holding ?mug)
     :effect (and
        (under ?mug ?holder)
        (not (holding ?mug))
        (free ?gripper))
    )


    (:action open-drawer
     :parameters (?drawer - drawer ?gripper - gripper)
     :precondition (and (not (open ?drawer)) (free ?gripper))
     :effect (and
        (open ?drawer))
    )

)