
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Domain file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (domain cleanup)
    (:requirements :equality :typing)
    (:types
        gripper - object
        table - object
        tabletop-object - object
        block - tabletop-object
        container - tabletop-object
        mug - container
        drawer - container
        object
    )

    (:constants
        
    )

    (:predicates
        (can-pick-up ?x1 - tabletop-object)
        (can-contain ?x1 - container ?x2 - tabletop-object)
        (on-table ?x1 - tabletop-object ?x2 - table)
        (occupying-gripper ?x1 - tabletop-object ?x2 - gripper)
        (in ?x1 - tabletop-object ?x2 - container)
        (open ?x1 - container)
        (free ?x1 - gripper)
    )

    (:functions
        
    )

    

    
    (:action pick-up-tabletop
     :parameters (?tabletop-object - tabletop-object ?table - table ?gripper - gripper)
     :precondition (and (on-table ?tabletop-object ?table) (can-pick-up ?tabletop-object) (free ?gripper))
     :effect (and
        (occupying-gripper ?tabletop-object ?gripper)
        (not (on-table ?tabletop-object ?table))
        (not (free ?gripper)))
    )


    (:action free-gripper
     :parameters (?tabletop-object - tabletop-object ?gripper - gripper)
     :precondition (and (not (can-pick-up ?tabletop-object)) (occupying-gripper ?tabletop-object ?gripper) (not (free ?gripper)))
     :effect (and
        (not (occupying-gripper ?tabletop-object ?gripper))
        (free ?gripper))
    )


    (:action open-drawer
     :parameters (?drawer - drawer ?gripper - gripper)
     :precondition (and (not (open ?drawer)) (free ?gripper))
     :effect (and
        (open ?drawer)
        (occupying-gripper ?drawer ?gripper)
        (not (free ?gripper)))
    )


    (:action close-drawer
     :parameters (?drawer - drawer ?gripper - gripper)
     :precondition (and (open ?drawer) (free ?gripper))
     :effect (and
        (not (open ?drawer))
        (occupying-gripper ?drawer ?gripper)
        (not (free ?gripper)))
    )


    (:action put-in-drawer
     :parameters (?drawer - drawer ?tabletop-object - tabletop-object ?gripper - gripper)
     :precondition (and (open ?drawer) (can-contain ?drawer ?tabletop-object) (occupying-gripper ?tabletop-object ?gripper) (not (free ?gripper)))
     :effect (and
        (in ?tabletop-object ?drawer)
        (not (occupying-gripper ?tabletop-object ?gripper))
        (free ?gripper))
    )


    (:action remove-from-mug
     :parameters (?block - block ?gripper - gripper ?mug - mug)
     :precondition (and (can-pick-up ?block) (and (free ?gripper) (and (in ?block ?mug) (open ?mug))))
     :effect (and
        (not (free ?gripper))
        (not (in ?block ?mug))
        (occupying-gripper ?block ?gripper))
    )

)