
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Domain file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (domain cleanup)
    (:requirements :equality :typing)
    (:types
        gripper - object
        table - object
        tabletop-object - object
        block - tabletop-object
        container - tabletop-object
        mug - container
        drawer - container
        object
    )

    (:constants
        
    )

    (:predicates
        (directly-on-table ?x1 - tabletop-object ?x2 - table)
        (exclusively-occupying-gripper ?x1 - tabletop-object ?x2 - gripper)
        (free ?x1 - gripper)
        (inside ?x1 - tabletop-object ?x2 - container)
        (large-enough-for-gripper-to-reach-inside ?x1 - container ?x2 - gripper)
        (open ?x1 - container)
        (small-enough-for-gripper-to-pick-up ?x1 - tabletop-object ?x2 - gripper)
        (small-enough-to-fit-in-container ?x1 - tabletop-object ?x2 - container)
    )

    (:functions
        
    )

    

    
    (:action pick-up-from-tabletop
     :parameters (?tabletop-object - tabletop-object ?table - table ?gripper - gripper)
     :precondition (and (directly-on-table ?tabletop-object ?table) (small-enough-for-gripper-to-pick-up ?tabletop-object ?gripper) (free ?gripper))
     :effect (and
        (exclusively-occupying-gripper ?tabletop-object ?gripper)
        (not (directly-on-table ?tabletop-object ?table))
        (not (free ?gripper)))
    )


    (:action free-gripper-from-large-object
     :parameters (?tabletop-object - tabletop-object ?gripper - gripper)
     :precondition (and (not (small-enough-for-gripper-to-pick-up ?tabletop-object ?gripper)) (exclusively-occupying-gripper ?tabletop-object ?gripper) (not (free ?gripper)))
     :effect (and
        (not (exclusively-occupying-gripper ?tabletop-object ?gripper))
        (free ?gripper))
    )


    (:action open-drawer
     :parameters (?drawer - drawer ?gripper - gripper)
     :precondition (and (not (open ?drawer)) (free ?gripper))
     :effect (and
        (open ?drawer)
        (exclusively-occupying-gripper ?drawer ?gripper)
        (not (free ?gripper)))
    )


    (:action close-drawer
     :parameters (?drawer - drawer ?gripper - gripper)
     :precondition (and (open ?drawer) (free ?gripper))
     :effect (and
        (not (open ?drawer))
        (exclusively-occupying-gripper ?drawer ?gripper)
        (not (free ?gripper)))
    )


    (:action place-in-drawer-from-gripper
     :parameters (?drawer - drawer ?tabletop-object - tabletop-object ?gripper - gripper)
     :precondition (and (open ?drawer) (small-enough-to-fit-in-container ?tabletop-object ?drawer) (large-enough-for-gripper-to-reach-inside ?drawer ?gripper) (exclusively-occupying-gripper ?tabletop-object ?gripper) (not (free ?gripper)))
     :effect (and
        (inside ?tabletop-object ?drawer)
        (not (exclusively-occupying-gripper ?tabletop-object ?gripper))
        (free ?gripper))
    )


    (:action tip-container-to-remove-object
     :parameters (?block - block ?gripper - gripper ?mug - mug ?table - table)
     :precondition (and (directly-on-table ?mug ?table) (free ?gripper) (inside ?block ?mug) (not (directly-on-table ?block ?table)) (not (exclusively-occupying-gripper ?block ?gripper)) (not (exclusively-occupying-gripper ?mug ?gripper)) (not (large-enough-for-gripper-to-reach-inside ?mug ?gripper)) (open ?mug) (small-enough-for-gripper-to-pick-up ?block ?gripper) (small-enough-for-gripper-to-pick-up ?mug ?gripper) (small-enough-to-fit-in-container ?block ?mug))
     :effect (and
        (directly-on-table ?block ?table)
        (exclusively-occupying-gripper ?mug ?gripper)
        (not (directly-on-table ?mug ?table))
        (not (free ?gripper))
        (not (inside ?block ?mug)))
    )


    (:action place-on-table-from-gripper
     :parameters (?gripper - gripper ?mug - mug ?table - table)
     :precondition (and (exclusively-occupying-gripper ?mug ?gripper) (not (directly-on-table ?mug ?table)) (not (free ?gripper)) (not (large-enough-for-gripper-to-reach-inside ?mug ?gripper)) (open ?mug) (small-enough-for-gripper-to-pick-up ?mug ?gripper))
     :effect (and
        (directly-on-table ?mug ?table)
        (free ?gripper)
        (not (exclusively-occupying-gripper ?mug ?gripper)))
    )

)