
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Domain file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (domain coffee)
    (:requirements :equality :typing)
    (:types
        gripper - object
        table - object
        tabletop-object - object
        coffee-pod - tabletop-object
        coffee-machine-lid - tabletop-object
        container - tabletop-object
        mug - container
        coffee-pod-holder - container
        drawer - container
        object
    )

    (:constants
        
    )

    (:predicates
        (small-enough-for-gripper-to-pick-up ?x1 - tabletop-object ?x2 - gripper)
        (can-flip-up ?x1 - coffee-machine-lid)
        (can-flip-down ?x1 - coffee-machine-lid)
        (directly-on-table ?x1 - tabletop-object ?x2 - table)
        (exclusively-occupying-gripper ?x1 - tabletop-object ?x2 - gripper)
        (attached ?x1 - coffee-machine-lid ?x2 - coffee-pod-holder)
        (in ?x1 - tabletop-object ?x2 - container)
        (open ?x1 - container)
        (free ?x1 - gripper)
        (under ?x1 - mug ?x2 - coffee-pod-holder)
    )

    (:functions
        
    )

    

    
    (:action pick-up-from-tabletop
     :parameters (?tabletop-object - tabletop-object ?table - table ?gripper - gripper)
     :precondition (and (directly-on-table ?tabletop-object ?table) (small-enough-for-gripper-to-pick-up ?tabletop-object ?gripper) (free ?gripper))
     :effect (and
        (exclusively-occupying-gripper ?tabletop-object ?gripper)
        (not (directly-on-table ?tabletop-object ?table))
        (not (free ?gripper)))
    )


    (:action open-coffee-pod-holder
     :parameters (?holder - coffee-pod-holder ?lid - coffee-machine-lid ?gripper - gripper)
     :precondition (and (not (open ?holder)) (can-flip-up ?lid) (attached ?lid ?holder) (free ?gripper))
     :effect (and
        (exclusively-occupying-gripper ?lid ?gripper)
        (can-flip-down ?lid)
        (open ?holder)
        (not (free ?gripper)))
    )


    (:action close-coffee-pod-holder
     :parameters (?holder - coffee-pod-holder ?lid - coffee-machine-lid ?gripper - gripper)
     :precondition (and (open ?holder) (can-flip-down ?lid) (attached ?lid ?holder) (free ?gripper))
     :effect (and
        (exclusively-occupying-gripper ?lid ?gripper)
        (not (open ?holder))
        (not (free ?gripper)))
    )


    (:action free-gripper-from-large-object
     :parameters (?tabletop-object - tabletop-object ?gripper - gripper)
     :precondition (and (not (small-enough-for-gripper-to-pick-up ?tabletop-object ?gripper)) (exclusively-occupying-gripper ?tabletop-object ?gripper) (not (free ?gripper)))
     :effect (and
        (not (exclusively-occupying-gripper ?tabletop-object ?gripper))
        (free ?gripper))
    )


    (:action place-pod-in-holder-from-gripper
     :parameters (?pod - coffee-pod ?holder - coffee-pod-holder ?gripper - gripper)
     :precondition (and (exclusively-occupying-gripper ?pod ?gripper) (open ?holder) (not (free ?gripper)))
     :effect (and
        (not (exclusively-occupying-gripper ?pod ?gripper))
        (in ?pod ?holder)
        (free ?gripper))
    )


    (:action place-mug-under-holder-from-gripper
     :parameters (?mug - mug ?holder - coffee-pod-holder ?gripper - gripper)
     :precondition (and (exclusively-occupying-gripper ?mug ?gripper) (not (free ?gripper)))
     :effect (and
        (under ?mug ?holder)
        (not (exclusively-occupying-gripper ?mug ?gripper))
        (free ?gripper))
    )


    (:action open-drawer
     :parameters (?drawer - drawer ?gripper - gripper)
     :precondition (and (free ?gripper) (not (exclusively-occupying-gripper ?drawer ?gripper)) (not (open ?drawer)) (not (small-enough-for-gripper-to-pick-up ?drawer ?gripper)))
     :effect (and
        (exclusively-occupying-gripper ?drawer ?gripper)
        (not (free ?gripper))
        (open ?drawer))
    )


    (:action pick-up-from-open-drawer
     :parameters (?coffee-pod - coffee-pod ?drawer - drawer ?gripper - gripper)
     :precondition (and (free ?gripper) (in ?coffee-pod ?drawer) (not (exclusively-occupying-gripper ?coffee-pod ?gripper)) (not (exclusively-occupying-gripper ?drawer ?gripper)) (not (small-enough-for-gripper-to-pick-up ?drawer ?gripper)) (open ?drawer) (small-enough-for-gripper-to-pick-up ?coffee-pod ?gripper))
     :effect (and
        (exclusively-occupying-gripper ?coffee-pod ?gripper)
        (not (free ?gripper))
        (not (in ?coffee-pod ?drawer)))
    )

)