
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Domain file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (domain coffee)
    (:requirements :equality :typing)
    (:types
        gripper - object
        table - object
        tabletop-object - object
        coffee-pod - tabletop-object
        coffee-machine-lid - tabletop-object
        container - tabletop-object
        mug - container
        coffee-pod-holder - container
        drawer - container
        object
    )

    (:constants
        
    )

    (:predicates
        (can-pick-up ?x1 - tabletop-object)
        (can-contain ?x1 - container ?x2 - tabletop-object)
        (can-flip-up ?x1 - coffee-machine-lid)
        (can-flip-down ?x1 - coffee-machine-lid)
        (on-table ?x1 - tabletop-object ?x2 - table)
        (occupying-gripper ?x1 - tabletop-object ?x2 - gripper)
        (attached ?x1 - coffee-machine-lid ?x2 - coffee-pod-holder)
        (in ?x1 - tabletop-object ?x2 - container)
        (open ?x1 - container)
        (free ?x1 - gripper)
        (under ?x1 - mug ?x2 - coffee-pod-holder)
    )

    (:functions
        
    )

    

    
    (:action pick-up-tabletop
     :parameters (?tabletop-object - tabletop-object ?table - table ?gripper - gripper)
     :precondition (and (on-table ?tabletop-object ?table) (can-pick-up ?tabletop-object) (free ?gripper))
     :effect (and
        (occupying-gripper ?tabletop-object ?gripper)
        (not (on-table ?tabletop-object ?table))
        (not (free ?gripper)))
    )


    (:action open-coffee-pod-holder
     :parameters (?holder - coffee-pod-holder ?lid - coffee-machine-lid ?gripper - gripper)
     :precondition (and (not (open ?holder)) (can-flip-up ?lid) (attached ?lid ?holder) (free ?gripper))
     :effect (and
        (occupying-gripper ?lid ?gripper)
        (can-flip-down ?lid)
        (open ?holder)
        (not (free ?gripper)))
    )


    (:action close-coffee-pod-holder
     :parameters (?holder - coffee-pod-holder ?lid - coffee-machine-lid ?gripper - gripper)
     :precondition (and (open ?holder) (can-flip-down ?lid) (attached ?lid ?holder) (free ?gripper))
     :effect (and
        (occupying-gripper ?lid ?gripper)
        (not (open ?holder))
        (not (free ?gripper)))
    )


    (:action free-gripper
     :parameters (?tabletop-object - tabletop-object ?gripper - gripper)
     :precondition (and (not (can-pick-up ?tabletop-object)) (occupying-gripper ?tabletop-object ?gripper) (not (free ?gripper)))
     :effect (and
        (not (occupying-gripper ?tabletop-object ?gripper))
        (free ?gripper))
    )


    (:action place-pod-in-holder
     :parameters (?pod - coffee-pod ?holder - coffee-pod-holder ?gripper - gripper)
     :precondition (and (occupying-gripper ?pod ?gripper) (open ?holder) (can-contain ?holder ?pod) (not (free ?gripper)))
     :effect (and
        (not (occupying-gripper ?pod ?gripper))
        (in ?pod ?holder)
        (free ?gripper))
    )


    (:action place-mug-under-holder
     :parameters (?mug - mug ?holder - coffee-pod-holder ?gripper - gripper)
     :precondition (and (occupying-gripper ?mug ?gripper) (not (free ?gripper)))
     :effect (and
        (under ?mug ?holder)
        (not (occupying-gripper ?mug ?gripper))
        (free ?gripper))
    )


    (:action remove-pod-from-drawer
     :parameters (?drawer - drawer ?gripper - gripper ?pod - coffee-pod)
     :precondition (and (can-pick-up ?pod) (and (free ?gripper) (in ?pod ?drawer)))
     :effect (and
        (not (free ?gripper))
        (not (in ?pod ?drawer))
        (occupying-gripper ?pod ?gripper))
    )

)